
------------------------------------------------Business Analysis-------------------------------------------

USE [Swiggy Database]

-- 1. Which cities consistently outperform and deserve expansion budget?



-- 2. Are we over-dependent on a few restaurants?



-- 3. Which dishes are overpriced for demand?


-- 4. When should operations scale up or down?


-- 5. Weekend vs Weekday Behavior


-- 6. Which restaurants are revenue-positive but brand-negative?